In [ ]:
import urllib.request
import pandas as pd

In [ ]:
def downloadurl(url, path):
    long_url = urllib.request.urlopen(url).geturl()
    urllib.request.urlretrieve(long_url, path)

downloadurl('https://bit.ly/ins1', "insurance.csv")

In [ ]:
df = pd.read_csv("./insurance.csv")
df.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

# 1.1 Görev
**Dataframe kullanarak datasetimizde "price_category" isimli yeni bir özellik (attribute, feature, kolon) ekleyeceksiniz.
"price_category"=0 if charges<10000
"price_category"=1 if charges>=10000 ve charges<=30000
"price_category"=2 if charges>30000**

In [ ]:
def price_category(charges):
    if charges < 10000:
        return 0
    elif 10000 <= charges <= 30000:
        return 1
    elif charges > 30000:
        return 2

df['price_category'] = df['charges'].apply(price_category)
df

age     sex     bmi  children smoker     region      charges  \
0      19  female  27.900         0    yes  southwest  16884.92400   
1      18    male  33.770         1     no  southeast   1725.55230   
2      28    male  33.000         3     no  southeast   4449.46200   
3      33    male  22.705         0     no  northwest  21984.47061   
4      32    male  28.880         0     no  northwest   3866.85520   
...   ...     ...     ...       ...    ...        ...          ...   
1333   50    male  30.970         3     no  northwest  10600.54830   
1334   18  female  31.920         0     no  northeast   2205.98080   
1335   18  female  36.850         0     no  southeast   1629.83350   
1336   21  female  25.800         0     no  southwest   2007.94500   
1337   61  female  29.070         0    yes  northwest  29141.36030   

      price_category  
0                  1  
1                  0  
2                  0  
3                  1  
4                  0  
...              ...  
1333               1  
1334               0  
1335               0  
1336               0  
1337               1  

[1338 rows x 8 columns]

## 1.2 Görev
**"Charges" feature'ını sileceksiniz.
NOT:İşlem sonunda datasetimizde aşağıdaki feature'lar bulunmalı:
age,sex,bmi,children,smoker,region,price_category**

In [ ]:
df = df.drop('charges', axis=1)
df

age     sex     bmi  children smoker     region  price_category
0      19  female  27.900         0    yes  southwest               1
1      18    male  33.770         1     no  southeast               0
2      28    male  33.000         3     no  southeast               0
3      33    male  22.705         0     no  northwest               1
4      32    male  28.880         0     no  northwest               0
...   ...     ...     ...       ...    ...        ...             ...
1333   50    male  30.970         3     no  northwest               1
1334   18  female  31.920         0     no  northeast               0
1335   18  female  36.850         0     no  southeast               0
1336   21  female  25.800         0     no  southwest               0
1337   61  female  29.070         0    yes  northwest               1

[1338 rows x 7 columns]

## 1.3 Görev
**Kategorik olan faeture'ları Label Encoding numerik hale getiriniz.
Hint:
from sklearn.preprocessing import LabelEncoder**

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
categorical_features = ['sex', 'smoker', 'region']
le = LabelEncoder()

In [ ]:
for f in categorical_features:
    df[f] = le.fit_transform(df[f])
df

age  sex     bmi  children  smoker  region  price_category
0      19    0  27.900         0       1       3               1
1      18    1  33.770         1       0       2               0
2      28    1  33.000         3       0       2               0
3      33    1  22.705         0       0       1               1
4      32    1  28.880         0       0       1               0
...   ...  ...     ...       ...     ...     ...             ...
1333   50    1  30.970         3       0       1               1
1334   18    0  31.920         0       0       0               0
1335   18    0  36.850         0       0       2               0
1336   21    0  25.800         0       0       3               0
1337   61    0  29.070         0       1       1               1

[1338 rows x 7 columns]

## 1.4 Görev
**Train (%80) ve test(%20) verilerini ayırın
NOT: Output (y_train, y_test) olarak "price_category", Input (X_train, X_test) olarak ise "price_category" dışındaki feature vektörlerini kulanacaksınız**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [ ]:
X = df.drop('price_category', axis=1)
y = df['price_category']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## 1.5 Görev
**Train ve test input değerlerinde StandardScaler kullanarak normalizasyon uygulayın.
Hint:
from sklearn.preprocessing import StandardScaler**

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## 1.6 Görev
**Support Vector Machine sınıflandırıcısı kullanarak modeli oluşturun ve eğitin.
Hint: from sklearn.svm import SVC**

In [ ]:
model = SVC()
model.fit(X_train, y_train)

SVC()

## 1.7 Görev
**Train ve test sklorlarını ekrana bastırın.**

In [ ]:
train_pred = model.predict(X_train)
train_acc = accuracy_score(y_train, train_pred)
print("Train setinin doğruluğu:", train_acc)

test_pred = model.predict(X_test)
test_acs = accuracy_score(y_test, test_pred)
print("Test setinin doğruluğu:", test_acs)

Train setinin doğruluğu: 0.9186915887850468
Test setinin doğruluğu: 0.9253731343283582


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

# 2.1

**Yukarıdaki işlemleri KNN (k-nearest neighbors) sınıflandırıcısı kullanarak tekrarlayın.
Hint:
from sklearn.neighbors import KNeighborsClassifier**

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
train_preds = knn.predict(X_train)
train_acc = accuracy_score(y_train, train_preds)
print("Train setinin doğruluğu:", train_acc)
test_preds = knn.predict(X_test)
test_acc = accuracy_score(y_test, test_preds)
print("Test setinin doğruluğu:", test_acc)

Train setinin doğruluğu: 0.8878504672897196
Test setinin doğruluğu: 0.8955223880597015


>> bonus

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [ ]:
print("Hassasiyet:", precision_score(y_test, test_preds, average='weighted'))
print("Doğruluk:", recall_score(y_test, test_preds, average='weighted'))
print("F1-Skor:", f1_score(y_test, test_preds, average='weighted'))
print("Karmaşıklık Matrisi:\n", confusion_matrix(y_test, test_preds))

Hassasiyet: 0.8955223880597015
Doğruluk: 0.8955223880597015
F1-Skor: 0.8955223880597015
Karmaşıklık Matrisi:
 [[135  12   0]
 [ 12  72   2]
 [  0   2  33]]
